[env:seeed-xiao-esp32s3]
platform  = espressif32
board     = seeed_xiao_esp32s3   ; change to seeed_xiao_esp32s3sense for Sense variant
framework = arduino

upload_speed  = 115200
monitor_speed = 115200

lib_deps =
    fastled/FastLED @ ^3.6.0

build_flags =
    -I src
    -DARDUINO_USB_CDC_ON_BOOT=1
